## Libraries

In [1]:
# pip install rapidfuzz

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from rapidfuzz import process, utils

## Import Dataset

In [3]:
#Import the training dataset
train = pd.read_csv('../original_datasets/train.csv')
train.head()

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
0,69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,63.0,4.000000,0.0
1,53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,50.0,1.000000,0.0
2,6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,56.0,4.000000,0.0
3,29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,50.0,-2.340306,0.0
4,10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,97.0,3.000000,0.0

In [4]:
#Import the test dataset
test = pd.read_csv('../original_datasets/test.csv')

In [5]:
test.head()

,carID,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
0,89856,Hyundai,I30,2022.878006,Automatic,30700.000000,petrol,205.0,41.5,1.6,61.0,3.0,0.0
1,106581,VW,Tiguan,2017.000000,Semi-Auto,-48190.655673,Petrol,150.0,38.2,2.0,60.0,2.0,0.0
2,80886,BMW,2 Series,2016.000000,Automatic,36792.000000,Petrol,125.0,51.4,1.5,94.0,2.0,0.0
3,100174,Opel,Grandland X,2019.000000,Manual,5533.000000,Petrol,145.0,44.1,1.2,77.0,1.0,0.0
4,81376,BMW,1 Series,2019.000000,Semi-Auto,9058.000000,Diesel,150.0,51.4,2.0,45.0,4.0,0.0

## Functions

We will use *functions* to facilitate our writting. All our functions will be stored in this section for easier readability. 

All functions will have their definitions.

In [6]:
correct_models = [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'A1',
    'A2',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'A Class',
    'Adam',
    'Agila',
    'Amarok',
    'Ampera',
    'Antara',
    'Arteon',
    'Astra',
    'Auris',
    'Avensis',
    'Aygo',
    'B Class',
    'B-MAX',
    'Beetle',
    'C Class',
    'C-HR',
    'C-MAX',
    'Caddy',
    'Caddy Maxi Life',
    'California',
    'Camry',
    'Caravelle',
    'Cascada',
    'CC',
    'Citigo',
    'CLA Class',
    'CLC Class',
    'CL Class',
    'CLK',
    'CLS Class',
    'Combo Life',
    'Corolla',
    'Corsa',
    'Crossland X',
    'E Class',
    'EcoSport',
    'Edge',
    'Eos',
    'Escort',
    'Fabia',
    'Fiesta',
    'Focus',
    'Fox',
    'Fusion',
    'G Class',
    'Galaxy',
    'Getz',
    'GL Class',
    'GLA Class',
    'GLB Class',
    'GLC Class',
    'GLE Class',
    'GLS Class',
    'Golf',
    'Golf SV',
    'Grand C-MAX',
    'Grand Tourneo Connect',
    'Grandland X',
    'GTC',
    'GT86',
    'Hilux',
    'i10',
    'i20',
    'i3',
    'i30',
    'i40',
    'i8',
    'i800',
    'Insignia',
    'Ioniq',
    'IQ',
    'IX20',
    'IX35',
    'Jetta',
    'Ka',
    'Ka+',
    'Kadjar',
    'Kamiq',
    'Karoq',
    'Kodiaq',
    'Kona',
    'Kuga',
    'Land Cruiser',
    'M2',
    'M3',
    'M4',
    'M5',
    'M6',
    'M Class',
    'Meriva',
    'Mokka',
    'Mokka X',
    'Mondeo',
    'Mustang',
    'Octavia',
    'Passat',
    'Polo',
    'Prius',
    'Proace Verso',
    'Puma',
    'Q2',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'R8',
    'Rapid',
    'RAV4',
    'Roomster',
    'RS',
    'RS3',
    'RS4',
    'RS5',
    'RS6',
    'S Class',
    'S-MAX',
    'S3',
    'S4',
    'S5',
    'S8',
    'Santa Fe',
    'Scala',
    'Scirocco',
    'Sharan',
    'Shuttle',
    'SL Class',
    'SLK',
    'SQ5',
    'SQ7',
    'Streetka',
    'Superb',
    'Supra',
    'T-Cross',
    'T-Roc',
    'Terracan',
    'Tigra',
    'Tiguan',
    'Tiguan Allspace',
    'TT',
    'Touareg',
    'Touran',
    'Tourneo Connect',
    'Tourneo Custom',
    'Tucson',
    'Up',
    'Urban Cruiser',
    'V Class',
    'Vectra',
    'Veloster',
    'Verso',
    'Verso-S',
    'Viva',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'X-CLASS',
    'Yaris',
    'Yeti',
    'Yeti Outdoor',
    'Z3',
    'Z4',
    'Zafira',
    'Zafira Tourer',
    'Unknown',
    '200',
    '220',
    '230'
]

In [7]:
correct_transmission = ['Manual', 'Semi-Auto', 'Automatic', 'Other','Unknown']
correct_fuelType = ['Petrol', 'Diesel', 'Hybrid', 'Electric', 'Other', 'Unknown']
correct_brand = ['VW', 'Toyota', 'Audi', 'Ford', 'Skoda', 'Opel', 'Mercedes', 'Hyundai', 'BMW', 'Unknown']

#Apply rapidfuzz to the features
def clean_strings(x, l):
    """
    Standardizes a single string value by using fuzzy matching against a list of correct values.

    It handles missing values, normalizes the input string, and attempts to find the 
    closest match in the provided list. If the match score is below a threshold (80), 
    or if the input is missing, the value is categorized as 'Unknown'.

    Args:
        x (str or object): The input string value (a single cell from a DataFrame column).
        l (list): The list of correct, allowed string values (e.g., correct_transmission).

    Returns:
        str: The standardized string value, which will be one of the values from the 
             correct list (l) or 'Unknown'.
    """
    if pd.isna(x):
        return 'Unknown'
    x = x.strip().title()
    match, score, _ = process.extractOne(x, l, processor=utils.default_process)    
    if score > 70:
        return match
    else:
        return 'Unknown'

## New Features

We will create new features, that we think that might help the model predict better the test dataset. This features are:

- **mileage_per_year**: We get how much the car is driven, on average, a year
- **tax_engineSize**: Some larger engines might have higher taxes, so, multiplying them, can exposes us a relationship the model find useful.
- **age_mileage**: With this feature we can get a extimation on the condition of the car

In [8]:
test['mileage_per_year'] = test['mileage'] / (2025 - test['year'])
train['mileage_per_year'] = train['mileage'] / (2025 - train['year'])

In [9]:
test['tax_engineSize'] = test['tax'] *  test['engineSize']
train['tax_engineSize'] = train['tax'] * train['engineSize']

In [10]:
test['age_mileage'] = (2025 - test['year']) *  test['mileage']
train['age_mileage'] = (2025 - train['year']) * train['mileage']

In [11]:
test['mpg_engineSize'] = test['mpg'] * test['engineSize']
train['mpg_engineSize'] = train['mpg'] * train['engineSize']

In [12]:
test['miles_mpg'] = test['mileage'] *test['mpg']
train['miles_mpg'] = train['mileage'] * train['mpg']

In [13]:
test['age'] = 2025 - test['year']
train['age'] = 2025 - train['year']

## Inconsistent Data

Has we seen in the Data Understanding file, there is some features that have problems in their data:
- Negative values
- Typos

#### Negative Data

For the negative data, we will use the *absolute values* to transform the incorrect data. First, we will create a list with the features that have these type of problem, and then, we use the method **abs()** to get the absolute value. Since the method doesn't get information of other rows in the dataset, we don't need to worry about leakage.

In [14]:
#Features where exists negavite data 
negative_features = ['mileage', 'mpg', 'engineSize', 'previousOwners', 'tax', 'mileage_per_year', 'tax_engineSize', 'age_mileage', 'miles_mpg', 'mpg_engineSize']

In [15]:
#Get the absolute value
train[negative_features] = train[negative_features].abs()
test[negative_features] = test[negative_features].abs()

In [16]:
train[negative_features].min()

mileage              1.000000
mpg                  1.100000
engineSize           0.000000
previousOwners       0.000000
tax                  0.000000
mileage_per_year     0.041667
tax_engineSize       0.000000
age_mileage          5.000000
miles_mpg           11.200000
mpg_engineSize       0.000000
dtype: float64

#### Typos

Also, as seen before, some categorical features have typos. To solve this problem we will use the library *rapidfuzz*. Rapizfuzz is a string matching library that will calculate the similarities between the words (the one in the list created and the ones from the dataset). For more efficient coding, we created a function (**clean_strings**) to apply the changes to the train and test dataset for the selected features.

##### Transmission

In [17]:
for df in [train, test]:
    df['transmission'] = df['transmission'].apply(lambda x: clean_strings(x, correct_transmission))

In [18]:
train['transmission'].value_counts()

transmission
Manual       41627
Semi-Auto    16872
Automatic    15211
Unknown       2258
Other            5
Name: count, dtype: int64

##### FuelType

In [19]:
for df in [train, test]:
    df['fuelType'] = df['fuelType'].apply(lambda x: clean_strings(x, correct_fuelType))

In [20]:
train['fuelType'].value_counts()

fuelType
Petrol      41181
Diesel      30885
Hybrid       2225
Unknown      1511
Other         167
Electric        4
Name: count, dtype: int64

##### Brand

In [21]:
for df in [train, test]:
    df['Brand'] = df['Brand'].apply(lambda x: clean_strings(x, correct_brand))

In [22]:
train['Brand'].value_counts()

Brand
Ford        16063
Mercedes    11674
VW          10385
Opel         9352
BMW          7392
Audi         7325
Toyota       4622
Skoda        4303
Hyundai      3336
Unknown      1521
Name: count, dtype: int64

#### Model

In [23]:
for df in [train, test]:
    df['model'] = df['model'].apply(lambda x: clean_strings(x, correct_models))

In [24]:
train['model'].value_counts()

model
Focus        6915
C Class      5288
Fiesta       4470
Golf         3261
Corsa        2319
             ...
A2              1
Fox             1
S5              1
CLC Class       1
Terracan        1
Name: count, Length: 186, dtype: int64

## Outliers

#### Year

In [25]:
train = train[train['year'] <= 2020]

#### Tax

In [26]:
train = train.assign(tax=pd.cut(df['tax'], bins=[0,120,240,360,480,600], labels=['0-120', '120-240', '240-360', '360-480', '480-600']))
test = test.assign(tax=pd.cut(df['tax'], bins=[0,120,240,360,480,600], labels=['0-120', '120-240', '240-360', '360-480', '480-600']))

In [27]:
train.head()

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage,mileage_per_year,tax_engineSize,age_mileage,mpg_engineSize,miles_mpg,age
0,69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,120-240,11.417268,2.0,63.0,4.000000,0.0,3157.888889,NaN,255789.0,22.834536,324490.166831,9.0
1,53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,120-240,47.900000,1.5,50.0,1.000000,0.0,764.833333,217.5,27534.0,71.850000,219813.100000,6.0
2,6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,120-240,40.900000,1.5,56.0,4.000000,0.0,604.000000,217.5,21744.0,61.350000,148221.600000,6.0
3,29021,Ford,Fiesta,2018.0,12500,Manual,9102.0,Petrol,120-240,65.700000,1.0,50.0,2.340306,0.0,1300.285714,145.0,63714.0,65.700000,598001.400000,7.0
4,10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,120-240,42.800000,1.5,97.0,3.000000,0.0,166.666667,217.5,6000.0,64.200000,42800.000000,6.0

In [28]:
train['tax'].value_counts()

tax
120-240    21217
0-120       4987
240-360      557
480-600       54
360-480        0
Name: count, dtype: int64

## Export

In [29]:
# Removemos 'carID' porque não é feature preditiva
# Mantemos 'price' fora do X_trainval
y_trainval = train['price']
X_trainval = train.drop(columns=['price', 'carID', 'paintQuality%', 'model', 'year'])

# Removemos 'carID' mas guardamo-lo se precisarmos dele para submissão (embora o Modeling o carregue do original)
X_test_final = test.drop(columns=['carID', 'paintQuality%', 'model', 'year'])

# Estes ficheiros vão conter Strings (ex: "Ford") e NaNs. É normal!
X_trainval.to_csv('../new_datasets/X_trainval_preprocessed.csv', index=False)
y_trainval.to_csv('../new_datasets/y_trainval.csv', index=False)
X_test_final.to_csv('../new_datasets/X_test_preprocessed.csv', index=False)

print("Dados exportados com sucesso! Prontos para o Loop Manual.")

Dados exportados com sucesso! Prontos para o Loop Manual.